[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider"
  # Disable Next.js plugin for Vite
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
