[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Explicitly disable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false
