[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  environment = { 
    NODE_VERSION = "18",
    NPM_FLAGS = "--legacy-peer-deps"
  }

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
